---
# tasks file for nexus
- include: prepare.yml
  become: yes

- include: install.yml

- include: configure.yml
  become: yes
  become_user: "{{ nexus_user }}"

- include: service-{{ ansible_os_family }}.yml
  become: yes
