---

- name: configure service
  template:
    src: nexus-service.j2
    dest: /etc/systemd/system/nexus.service

- name: enable service
  command: systemctl daemon-reload
  ignore_errors: yes

- name: enable service
  command: systemctl enable nexus.service
  ignore_errors: yes

- name: start service
  command: systemctl start nexus.service
  ignore_errors: yes
