Vagrant.configure(2) do |config|
  config.vm.network "private_network", type: "dhcp"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
    ansible.galaxy_role_file = "roles.yml"
  end

  config.vm.define "test01" do |node|
    node.vm.box = "jeqo/oracle-jdk-8-centos7"
  end

  config.vm.define "test02" do |node|
    node.vm.box = "jeqo/oracle-jdk-8-centos7"
  end
end
